// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Truck.Data.Context;

#nullable disable

namespace Truck.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Truck.Domain.Models.ModelTruck", b =>
                {
                    b.Property<int>("IdModel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModel"), 1L, 1);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdModel");

                    b.ToTable("ModelTruck");

                    b.HasData(
                        new
                        {
                            IdModel = 1,
                            Model = "FH"
                        },
                        new
                        {
                            IdModel = 2,
                            Model = "FM"
                        },
                        new
                        {
                            IdModel = 3,
                            Model = "Outer"
                        });
                });

            modelBuilder.Entity("Truck.Domain.Models.Truck", b =>
                {
                    b.Property<int>("IdTruck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTruck"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdModel")
                        .HasColumnType("int");

                    b.Property<int>("YearFabrication")
                        .HasColumnType("int");

                    b.Property<int>("YearModel")
                        .HasColumnType("int");

                    b.HasKey("IdTruck");

                    b.HasIndex("IdModel");

                    b.ToTable("Truck");
                });

            modelBuilder.Entity("Truck.Domain.Models.Truck", b =>
                {
                    b.HasOne("Truck.Domain.Models.ModelTruck", "ModelTruck")
                        .WithMany("Trucks")
                        .HasForeignKey("IdModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelTruck");
                });

            modelBuilder.Entity("Truck.Domain.Models.ModelTruck", b =>
                {
                    b.Navigation("Trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
