//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Truck.CrossCuting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesCrossCuting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesCrossCuting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Truck.CrossCuting.ResourcesCrossCuting", typeof(ResourcesCrossCuting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano Fabricação deve ser ano atual.
        /// </summary>
        public static string msgAnoFabricacaoDeveSerAnoAtual {
            get {
                return ResourceManager.GetString("msgAnoFabricacaoDeveSerAnoAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano Modelo deve ser ano atual ou subSequente.
        /// </summary>
        public static string msgAnoModeloDeveSerAnoAtualOuSubSequente {
            get {
                return ResourceManager.GetString("msgAnoModeloDeveSerAnoAtualOuSubSequente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list is empty!.
        /// </summary>
        public static string msgListEmpty {
            get {
                return ResourceManager.GetString("msgListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo deve der &quot;FH&quot; ou &quot;FM&quot;.
        /// </summary>
        public static string msgModeloDeveSerFHouFM {
            get {
                return ResourceManager.GetString("msgModeloDeveSerFHouFM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register already Exist!.
        /// </summary>
        public static string msgRegisterAlreadyExist {
            get {
                return ResourceManager.GetString("msgRegisterAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Not Found!.
        /// </summary>
        public static string msgRegisterNotFound {
            get {
                return ResourceManager.GetString("msgRegisterNotFound", resourceCulture);
            }
        }
    }
}
